[package]
name = "dispatchers"
version = "0.1.0"
edition = "2021"
description = "A message dispatcher trait and some implementations"
repository = "https://github.com/quantmind/dispatchers"
readme = "README.md"
license-file = "LICENSE"


[dependencies]
tokio = { version = "1.25.0", features = ["sync"], optional = true }


[features]
async = ["tokio"]


[[example]]
name = "mutable"
path = "examples/mutable.rs"
