[package]
name = "dispatcher"
version = "0.1.0"
edition = "2021"
description = "A simple message dispatcher"
repository = "https://github.com/quantmind/dispatcher"
readme = "README.md"
licence = "MIT"


[dependencies]



[[example]]
name = "mutable"
path = "examples/mutable.rs"
