[package]
name = "dispatchers"
version = "0.2.0"
edition = "2021"
description = "A message dispatcher trait and some implementations"
repository = "https://github.com/quantmind/dispatchers"
readme = "README.md"
license-file = "LICENSE"
exclude = [
    "justfile",
]


[dependencies]
async-trait = { version = "0.1.64", optional = true }
tokio = { version = "1.25.0", features = ["full"], optional = true }


[features]
shared = ["async-trait", "tokio"]


[[example]]
name = "mutable"
path = "examples/mutable.rs"

[[example]]
name = "broadcaster"
path = "examples/broadcaster.rs"

[[test]]
name = "tests"
path = "tests/test_dispatchers.rs"
