---
name: build

on:
  push:
    branches-ignore:
      - no-build

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install latest stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: stable
      - name: Install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run cargo checks
        run: just lint
      - name: Run cargo checks
        run: just lint
      - name: Run mutable example
        run: just mutable
      - name: Run broadcaster example
        run: just broadcaster
